name: Deploys

on:
  push:
    branches:
      - main

jobs:
  deploy-app-climatico:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          cd packages/app-climatico
          npm install
          npm run build

      - name: Deploy project
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Usa el token de GitHub Actions
          publish_dir: ./packages/app-climatico/dist # Carpeta con los archivos construidos
